//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePlan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceEntities : DbContext
    {
        public FinanceEntities()
            : base("name=FinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbSpending> tbSpending { get; set; }
        public virtual DbSet<tbUsers> tbUsers { get; set; }
        public virtual DbSet<tbCapitals> tbCapitals { get; set; }
        public virtual DbSet<tbCredits> tbCredits { get; set; }
        public virtual DbSet<tbCurrency> tbCurrency { get; set; }
        public virtual DbSet<tbMethod> tbMethod { get; set; }
        public virtual DbSet<tbProfits> tbProfits { get; set; }
        public virtual DbSet<tbServices> tbServices { get; set; }
    }
}
